version: '3.8'

services:
  minecraft:
    image: itzg/minecraft-server:${MC_CONTAINER_VERS}
    container_name: minecraft
    hostname: minecraft
    ports:
      - "${MC_SERVER_PORT}:25565"
      - 8888:8123
    volumes:
      - ./mc:/data
    environment:
      EULA: "TRUE"
      ENABLE_AUTOPAUSE: "TRUE"
      OVERRIDE_SERVER_PROPERTIES: "TRUE"
      MAX_TICK_TIME: "-1"
      TZ: America/Chicago
      VERSION: ${MC_SERVER_VERS}
      MOTD: ${MC_SERVER_MOTD}
      # WHITELIST: ${MC_SERVER_WHITELIST}
      ENABLE_WHITELIST: true
      OVERRIDE_WHITELIST: false
      MEMORY: 16G
      TYPE: spigot
    restart: always
  minecraft-backup:
    image: itzg/mc-backup
    depends_on:
      minecraft:
        condition: service_healthy
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: minecraft
    volumes:
      - ./mc:/data:ro
      - ./mc-backups:/backups